# This is a basic workflow that is manually triggered

name: Publish package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Publish to npm
      run: npm publish
    - name: Publish to github packages
      run: |
        npm login --registry=https://npm.pkg.github.com --scope:@nangurepo
        npm publish
      
